# Generated by Django 4.2.20 on 2026-08-03 03:17

import uuid

from django.db import migrations, models


def unique_tokens(apps, schema_editor):
    """AddField evaluates a callable default ONCE, so every existing row ends up
    sharing a single token — which would make the token useless as an access key.
    Give each order its own."""
    Order = apps.get_model('restaurant', 'Order')
    for pk in Order.objects.values_list('pk', flat=True):
        Order.objects.filter(pk=pk).update(access_token=uuid.uuid4())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_orderitem_combo_and_totals_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable key so a bill can be shared by link without exposing every other order'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='off_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% OFF (for percent type)', max_digits=5),
        ),
        migrations.RunPython(unique_tokens, noop),
    ]
