# Generated by Django 4.2.20 on 2026-08-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_order_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='is_offer',
            field=models.BooleanField(default=False, help_text='Show this as a Combo Offer at the top of the customer menu'),
        ),
        migrations.AddField(
            model_name='combo',
            name='offer_tag',
            field=models.CharField(blank=True, default='', help_text='Small badge text, e.g. LIMITED TIME', max_length=40),
        ),
        migrations.AddField(
            model_name='combo',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Optional: offer starts on this date', null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Optional: offer ends after this date', null=True),
        ),
    ]
