# Generated by Django 4.2.20 on 2026-08-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_combo_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoffer',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Optional: starts on this date. Blank = runs immediately.', null=True),
        ),
        migrations.AddField(
            model_name='cartoffer',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Optional: ends after this date. Blank = runs indefinitely.', null=True),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Optional: starts on this date. Blank = runs immediately.', null=True),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Optional: ends after this date. Blank = runs indefinitely.', null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='water_bottle_item',
            field=models.ForeignKey(blank=True, help_text='Which menu item the cart quick-add uses. Leave blank to auto-detect by name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurant.menuitem'),
        ),
    ]
