# Generated by Django 4.2.20 on 2026-08-04 14:40

from django.db import migrations, models


def flag_existing(apps, schema_editor):
    """Anything already named like a water bottle is marked automatically, so
    the setting has something to offer without manual work."""
    MenuItem = apps.get_model('restaurant', 'MenuItem')
    MenuItem.objects.filter(name__icontains='water').update(is_water_bottle=True)


def noop(apps, schema_editor):
    pass
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_offer_windows_and_water_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_water_bottle',
            field=models.BooleanField(default=False, help_text='Mark this as a water bottle so it can be used for the cart quick-add card'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='water_bottle_item',
            field=models.ForeignKey(blank=True, help_text='Which water bottle the cart quick-add uses. Only items marked as a water bottle can be chosen.', limit_choices_to={'is_water_bottle': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurant.menuitem'),
        ),
        migrations.RunPython(flag_existing, noop),
    ]
